### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by tony**
To keep it standardized as possible, I will use `setup.py` + requirements files. Example: [setup.py](https://github.com/cihai/cihai/blob/master/setup.py), [requirements/](https://github.com/cihai/cihai/tree/master/requirements).

## Examples:

`pip install -e .` - install as editable package

####  Extras (for [bumbleebee modules](https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules))

[setuptools](https://setuptools.readthedocs.io/en/latest/index.html) supports optional dependencies via "[extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)". Automatically grabs dependencies python packages.

`pip install -e '.[cpu]'`

`pip install -e '.[cpu,cpu2]'`

In practice, once on pypi, assuming `bumblee-status` is registered by you

`pip install bumblebee-status`

`pip install 'bumblebee-status[cpu]'`

`pip install 'bumblebee-status[cpu,yubikey]'`

## How to deploy

Go to pypi, register

`pip install twine`

`twine login`

`python setup.py sdist`

`twine upload dist/*`

Remember to `git tag v<versionNumber>` and update `__version__` in `__about__.py` before.

### CODE REVIEW

**Comment by tony** [comment]
Future tweaks (depending on how well poetry/pipenv/etc are supported): We could use [poetry](https://github.com/python-poetry/poetry) to manage the python package. But I've never done it before.

Here's an example of a project using [poetry](https://github.com/tony/django-docutils/blob/master/pyproject.toml) + [setup.py](https://github.com/tony/django-docutils/blob/master/setup.py): https://github.com/tony/django-docutils

**Comment by tony** [comment]
@tobi-wan-kenobi While I'm here, do you want me to add formatting, linting, import sorting?  Examples: [setup.cfg](https://github.com/cihai/cihai/blob/master/setup.cfg)

Would you like me to add a stub py.test example?

**Comment by tobi-wan-kenobi** [comment]
Great, many thanks!

Just a heads up: It'll likely take until next weekend for me to have time to properly review the PR, sorry about that.

Also: I will gladly look at anything you want to/have time to contribute (lint, test)

Many many thanks!

⁣

**Comment by tony** [comment]
@tobi-wan-kenobi

> Just a heads up: It'll likely take until next weekend for me to have time to properly review the PR, sorry about that.

That's fine!

Also feel no issue with forking this PR and modifying it directly if it doesn't fit your vision for what you'd like.

I'll do my best to strike a balance of what's pythonic / pypi compatible (and also friendly to package maintainers in the process).

 > Also: I will gladly look at anything you want to/have time to contribute (lint, test)

I think these may be best to add on after this PR, since it may expand the scope too much (linting / imports feels like a subject of its own)

**Comment by tony** [comment]
@tobi-wan-kenobi 

I did a very very minimal example that stays standard-friendly. This is open-ended, so if you merged, you could continue to tweak and be pretty safe.

After this, I'd recommend making a PyPI project on their website ASAP so you can reserve the project name. I can also do it on your behalf at your request.

Also rewrite README.md -> README.rst so it's pypi compatible. I can help with that if you'd like in another PR.

**Comment by tobi-wan-kenobi** [comment]
@tony Many thanks, will merge that right away and look into all that stuff as soon as possible, at least into registering the project.

**Comment by tobi-wan-kenobi** [comment]
@tony Just one more things: According to the pypi docs, markdown should be fine, or am I wrong? If not, I'll just use pandoc to create a rough rst :)

**Comment by tony** [comment]
@tobi-wan-kenobi In that case, even better if markdown is supported!

**Comment by tobi-wan-kenobi** [comment]
https://pypi.org/project/bumblebee-status/0.1.0/

Thanks for your help!

**Pull request merged**
