### PR TITLE
Add caffeine module

### PR DESCRIPTION
**Pull request by paxy97**
This module allows you to easily toggle between preventing the screen from turning off and default behaviour. I quite liked the extension available on gnome as it allows you to keep the screen on while watching long youtube videos, so my friend and I ported it to bumblebee, albeit much simpler and with less functionality.

Also, would you mind if I post this project on reddit? I think the folks there would enjoy it.

### CODE REVIEW

**Comment by paxy97** [comment]
Oh, i forgot to ask. There are two commented lines in my code, the add_callback calls. I tried to give it two commands as the cmd parameter, specifically with a ; and &, neither worked. Is there a way to have the button press run two commands without creating an external script? Maybe pass it an array of commands? I don't yet have enough confidence in my python knowledge (I just started) to change the backend

**Comment by tobi-wan-kenobi** [comment]
Hi,

regarding the callbacks: Please see c1123fa0839257e8d33f0a1d28a5ddb8709e5c0f, should be fixed there.

regarding reddit: Absolutely, feel free to do so, I'm happy if you think it's worth the while. I'd be grateful if you could drop me the link, too. Thanks a lot!

**Comment by tobi-wan-kenobi** [comment]
I also took the liberty of immediately activating the commented-out commands, please let me know if i should revert that particular change (027541126dcd7a0c0142cc8997a858dd8579c5a7)

**Comment by paxy97** [comment]
No, no thatnk you for fixing it. I posted it on reddit, [here's the link](https://www.reddit.com/r/unixporn/comments/5eoome/i3wm_with_bumblebee_status_and_gruvbox_colors/k, though I may post on the i3 sub as welle

**Pull request merged**
