### PR TITLE
add test for util.which

### PR DESCRIPTION
**Pull request by donfranio**
* and make runtests.sh dash-compatible for debian-like OS

### CODE REVIEW

**Comment by donfranio** [comment]
I am playing around finding my way to testing in python ... hope you like it.

**Comment by tobi-wan-kenobi** [comment]
Looks good to me, thanks! Also grateful for the bash improvement, not my strongest suit ;)

One idea for future improvement: It *might* make sense to ensure that the binary is executable, in the future. Also, also, for installations that don't have iwgetid, it might make sense to test for some basic binary that is present all the time (`ls` or something like that). I suspect that in Travis, it'll just always fall into the "None" case.

**Comment by donfranio** [comment]
Hi @tobi-wan-kenobi,
sorry for checking back that late.

1. You are correct, the test would be more precise, if it also checked the x-bit in the file-system.
2. If you would test the existence of ```ls``` then you would only test the test, right? So I would rather go into the direction to run all tests also on a debian-system with wireless-tools installed (of course in some container). This way you find such error in the pipeline already if something changes in debian itself.
3. (a fresh thought) In my opinion it could be useful, if the user recognized, that bumblebee-status is not able to show the essid at all.

What do you say?

**Comment by donfranio** [comment]
Hi again,

So it sure is no problem to iterate in the test over a list of (maybe) used binaries and adding something that needs to be there is surely easy.
Maybe adding some garbage that should never find a binary is a good idea as well. So if you had a second testing environment in the future the "none" path would stay checked.
I will put the stuff into a PR later.
Cu

**Pull request merged**
