### PR TITLE
Add parameter to specify a configuration file

### PR DESCRIPTION
**Pull request by michalroxorpl**
Hello, 
Like many of us, I am using a two display setup, I wanted to have different bars showing different information. 
It was not possible to instruct bumblebee-status to use selected / given configuration file (as it iterates over three preselected locations only).
I have created a working setup meeting this requirement, I am starting two status_commands in i3wm like this:
```
bar {
  position top
  output %DISP_INT
  tray_output %DISP_INT
  status_command /usr/bin/bumblebee-status -c ~/.config/bumblebee-status/config_main
}
bar {
  position bottom
  output %DISP_EXT
  tray_output none
  status_command /usr/bin/bumblebee-status -c ~/.config/bumblebee-status/config_external
}
```
I have now two different bars with separate configurations running. 
I love bumblebee-status and thank you for your work on it.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Many thanks for the contribution, this is a very useful change and the code looks fine!

Will merge right away.

**Comment by Tonus1** [comment]
That's a great improvement in my opinion (I had huge lines in i3 config to achieve this). What about another point release ?

**Comment by tobi-wan-kenobi** [comment]
@Tonus1 Good suggestion! I will try tocrelease a new version this week.

**Comment by tobi-wan-kenobi** [comment]
@Tonus1 v2.1.2 is now out on aur and pypi.

**Pull request merged**
