### PR TITLE
supported more tags

### PR DESCRIPTION
**Pull request by P-Storm**
More MPD tags support. First time using Python so feel free to comment on my code :)

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Looks good to me, thanks for the contribution!

Except the "tags" dict should actually be an array ([]), no? I'll merge the PR and update that manually, please let me know if that is a mistake on my side.

**Comment by P-Storm** [comment]
I was looking for a 'set' collection, so no multiple same strings could be in the collection. Did I make it a dictionary on mistake?

**Comment by tobi-wan-kenobi** [comment]
Oh, sorry, you are right! I will revert my changes again as soon as possible.

Thanks again for the PR!

⁣

**Comment by P-Storm** [comment]
@tobi-wan-kenobi 
Should the Syntax for these items be updates in the Available Modules list under Notes? Like the link 'https://www.mankier.com/1/mpc'

**Pull request merged**
