### PR TITLE
Spotify buttons module

### PR DESCRIPTION
**Pull request by LtPeriwinkle**
I saw issue #577 and thought it seemed like an interesting idea, so I copied the original Spotify module and added widgets for playback control to it. I'm not exactly a python genius, so it probably isn't as good as someone who is would do, but I thought it might be useful.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Very, very cool, thanks a lot!

2 minor suggestions/requests:

- For the layout, could you please use `util.format.aslist()`? That way, all lists are uniform (comma-separated) - that's particularly because argument parsing otherwise requires you to put the layout in quotes, I believe.
- I know it's tempting to split this out into a separate module, but to avoid confusiong for users (and I think buttons are useful for *everyone*, would you be OK if this simply replaces the current spotify module?

Thanks a lot for your contribution!

**Comment by martindoublem** [comment]
>     * I know it's tempting to split this out into a separate module, but to avoid confusiong for users (and I think buttons are useful for _everyone_, would you be OK if this simply replaces the current spotify module?

Ideally having the buttons as a parameter and the text as another would be better if you ask me, with both enabled by default would be great!

**Comment by tobi-wan-kenobi** [comment]
Looks good to me, thanks! In the future, it *might* be worth to remove the hardcoded unicode characters and replace them with theme info, like `cmus` does, for example, but other than that, this looks great. Many thanks!

**Comment by LtPeriwinkle** [comment]
Something a little strange (this might even be isolated to my machine), but since I overwrote the original spotify with the new version, most clicks on a button seem to register many times (for example skipping the entire playlist instead of one song, or playing and pausing super fast until the music just sounds like static) and it even blocks playing and pausing on the spotify window itself. I don't know what would cause this though (or how to fix it), and in case it's not isolated, I just wanted to let you know.

**Comment by tobi-wan-kenobi** [comment]
OK, that's good to know, thanks. I'll look into the code whether I spot something.

**Pull request merged**
