### PR TITLE
disk module: added remaining space option + bug fix

### PR DESCRIPTION
**Pull request by Kymon**
Enhancement of disk module which shows remaining space on disk.
Turning it on/off with parameter disk.showRemain="yes/no" (default yes).

Fixed bug caused by disk.showPercent="no".

### CODE REVIEW

**Comment by fredj** [comment]
And what about adding a new `format` option like it was done for the memory module in #143?

**Comment by Kymon** [comment]
That would be neat. I will change this soon.

**Comment by Kymon** [comment]
I guess everything is done.

**Comment by tobi-wan-kenobi** [comment]
That looks great, thanks!

One small thing, though: I'd love it if we could keep backwards compatibility by setting the default format string depending on whether any of the "show" flags are present (we can mark them as "deprecated", though). Does that sound fine for you?

I can do the change myself, but will probably only have time on the weekend, I'm pretty busy at work, right now. :(

**Comment by tobi-wan-kenobi** [comment]
@Kymon what do you think about the proposed patch?

It makes the code less beautiful (thanks for the nice cleanup, by the way!), but it should be backwards-compatible now.

**Comment by fredj** [comment]
@tobi-wan-kenobi you're patch looks good. I'm not using the battery module so I'm not the best person to ask ...

**Comment by Kymon** [comment]
@tobi-wan-kenobi it's fine.

**Comment by tobi-wan-kenobi** [comment]
thanks a lot for your feedback!

**Pull request merged**
