### PR TITLE
publicip module - Fixed bug and minor improvements in output

### PR DESCRIPTION
**Pull request by tfwiii**
Handled fail where core.location does not provide values for latitude and longitude. Added handling for coordinates N, S, E, W.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
thank you very much for the PR!

I addes 2 small remarks in the code directly, once we address those, the PR is ready to be merged, from my PoV.

**Comment by tfwiii** [comment]
Can't see you comments but presume they related to the debugging prints I had left in the code. Apologies for that, they are now removed!

**Comment by tobi-wan-kenobi** [comment]
thanks! exactly :)

the other thing i don't understand is line 129. to my understanding, __lon and __lat are never initialized, am i missing something? so basically, it wozld always display unknown, because the fields are not extracted from __info.

maybe it is just the github formatting, i am on mobile right now.

**Comment by tfwiii** [comment]
I think you're right! I'm sorry, I rushed this before going out and I obviously didn't test it enough. Let me take another look when I get home and I'll update...

**Comment by tobi-wan-kenobi** [comment]
Looking good now, thank you very much for your contribution!

**Pull request merged**
