### PR TITLE
[module/cpu2] add module

### PR DESCRIPTION
**Pull request by somospocos**
A Frankenstein CPU module.

bar

### CODE REVIEW

**Comment by somospocos** [comment]
Updated screenshot after fixing fan icon:

bar

**Comment by tobi-wan-kenobi** [comment]
Looks good, many thanks!

**Comment by somospocos** [comment]
There's a small inconsistency in https://github.com/tobi-wan-kenobi/bumblebee-status/wiki/Available-Modules : cpu module only requires psutil python module, while this one (cpu2) requires both psutil python module and sensors executable.

**Comment by tobi-wan-kenobi** [comment]
Fixed, thanks!

**Pull request merged**
