### PR TITLE
added module

### PR DESCRIPTION
**Pull request by DTan13**
Added module for [Blugon](https://github.com/jumper149/blugon)

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot for your contri ution!

A minor detail in the test aside, I think the code looks good and can be merged.

**Comment by DTan13** [comment]
Let's not merge this right now. I'll continue to work on it for a while more.

**Comment by tobi-wan-kenobi** [comment]
@DTan13 Is the PR ready to merge from your perspective? Aside from `zpool` in the tests, it looks fine for me.

**Comment by DTan13** [comment]
Ok

**Pull request merged**
