### PR TITLE
[module] New module pomodoro timer

### PR DESCRIPTION
**Pull request by martindoublem**
Created the pomodoro timer module, tested on my machine and worked fine.

Based on the work initialy done by karthink. In issue #434

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Thanks a lot!

It would be really great to have a pomodoro module in bumblebee. The Travis failure in Python 2.7 looks like a fluke, like it's trying to use bumblebee's datetime module instead of the Python module, but I'll need to investigate that during the weekend in a bit more detail.

**Comment by martindoublem** [comment]
Ideally there is probably a few things we can add and change to make it look good, like the times in config for each, like work and play.

**Comment by tobi-wan-kenobi** [comment]
The module looks fine, I'll just go ahead and merge it :)

**Comment by karthink** [comment]
Thank you Martin!

@tobi: I want to add two things to the module
1. An icon/unicode character. I looked at the spotify and redshift modules to see how they do it, and I can't find the character anywhere.
2. To highlight the display when the timer is running, the way the bluetooth module is lit up when bluetooth is on, or the CPU module is at high usage. But I can't see where to define this behavior.

**Comment by tobi-wan-kenobi** [comment]
Hi @karthink ,

good ideas!

Reg. 1 (icons): Please have a look at the themes in the themes/ subdirectory in general, and in particular at the themes/icons/ subdirectory. There, icons (prefixes and postfixes) for all modules are defined. If you add a definition for "pomodoro", you should get the icons automatically.

Reg. 2 (highlights): That's achieved via the `def state(self, widget)` method of a module. If the module returns "warning", it'll automatically get colored like a warning (typically yellow), if it returns "critical", it will get colored red (or whatever the theme says). You can use arbitrary status strings, but if it's something other than "critical" or "warning", you need to manually adapt the themes to add coloring for that.

Hope that helps!

**Comment by karthink** [comment]
off
work
paused
break

Added color definitions and icons for most themes and all icon packs. It's different colors for each theme to try and blend in, but it's not a perfect match everywhere. The gruvbox and solarized themes will work best.

Also tweaked the text descripton to be shorter, since the icons convey information about the state.

I forked it to make the changes, I want to make a couple more before submitting a pull request.

1. How do I set module parameters from the command line? I checked out nic.py because it has a lot of those, but I'm not seeing how they work.
2. Along the same lines, I want to add a command line parameter that lets the user specify a "bell" command to call when the timer runs out, like `bumblebee-status -m pomodoro -p pomodoro.bell="notify-send Time up"`. How would I do that?

**Comment by karthink** [comment]
Found better icons from the font-awesome pack.
off_000
work_000
paused_001
break_000

**Comment by martindoublem** [comment]
Alright, there are a couple settings (think config) I would like to set:

- Decide wether to display seconds or not.
- Have an option to change Work time and break time

@karthink , did you merge your changes yet?

**Comment by martindoublem** [comment]
Alright, there are a couple settings (think config) I would like to set:

- Decide wether to display seconds or not.
- Have an option to change Work time and break time

@karthink , did you merge your changes yet?

**Comment by karthink** [comment]
@martindoublem No the changes are in my forked repo right now. If you know how to make it configurable you can take over. Looks like we need the following configurable options:

1. A bell command to ring at the end of the work/break periods
2. Work and break durations
3. Time display option for minutes/minutes+seconds.

**Comment by tobi-wan-kenobi** [comment]
@karthink that looks real nice!

Regarding your questions:

1. Parameters can be defined using `self.parameter(<parameter name>, <default value>)`. Check out datetime.py for an example.
2. For notify, there's sample code in caffeine.py. It is really straight-forward.

Hope this helps! Looking forward to the PR a lot!

**Comment by karthink** [comment]
OK I created a pull request.

> 1. A bell command to ring at the end of the work/break periods
> 2. Work and break durations
> 3. Time display option for minutes/minutes+seconds.

All of these are implemented, #3 is fully configurable with a user-supplied string format.

**Pull request merged**
