### PR TITLE
.travis.yml: Install declared PyPI dependencies

### PR DESCRIPTION
**Pull request by jayvdb**
Related to https://github.com/tobi-wan-kenobi/bumblebee-status/issues/741

### CODE REVIEW

**Comment by jayvdb** [comment]
Hmm.  It seems Travis CI isnt being used?
I have a build started at https://travis-ci.org/github/jayvdb/bumblebee-status/builds/747325534

**Comment by tobi-wan-kenobi** [comment]
Yes, Travis is having issues since yesterday, I am working on fixing it. It seems the builds stay in the queue forever.

**Comment by tobi-wan-kenobi** [comment]
hm, looks like dbus needs to be removed....

**Comment by tobi-wan-kenobi** [comment]
The diff looks totally fine for me, I will merge it and fix Travis later.

Many thanks for proving bumblebee-status!

**Comment by jayvdb** [comment]
libvirt is going to need another APT package.  Do you want me to sort it out?

**Comment by tobi-wan-kenobi** [comment]
if you have time and inclination, that would be terrific.

alternatively, i'd probably just skip dbus and libvirt for now... 

not 100% sure i am willing to drop 3.5 support because of the dbus dep....

**Pull request merged**
