### PR TITLE
[modules/cmus] Add cmus.layout property to configure which widgets ar…

### PR DESCRIPTION
**Pull request by tobyp**
This PR adds:
- the `cmus.layout` parameter, which defaults to the space-separated list `cmus.prev cmus.main cmus.next cmus.shuffle cmus.repeat` and can be used to select/arrange the widgets created by the cmus module. Their functionality remains the same.

Currently, the cmus module will always add widgets for the actions "Previous", "Next", "Shuffle", and "Repeat", as well as a "Play/Pause" action on the main widget.
Play, Previous and Next can often be mapped to hardware keys, and Shuffle/Repeat are not needed as often, and probably go together with more complex configuration that requires access to the main cmus screen anyway.
Therefore, to save space in the bar for more of bumblebee's delicious widgets, users can now select which widgets they want on their screen.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Hi! Thanks a lot for the PR, that's a really really nice idea that I'd dearly like to see in `master`.

Unfortunately, the current implementation only works for Python 3.6+, because only there, the standard `dict` inserts keys in order. For older Pythons, the order depends on the map hashing.

Since you don't seem to need the map anywhere, my suggestion would be to switch widget_map to a list to which you simply append. Does that sound like an OK approach to you?

**Comment by tobyp** [comment]
Good catch!

I've updated my PR to use a list. The purpose of the map is to remember input callbacks and register them *after* the widgets are added. This is the order in which the old version did it, but it doesn't seem to matter to the engine/module as far as I can tell. Intuitively I would expect that the widgets have to be known to the engine before callbacks can be registered, so I kept it.

Please let me know your thoughts on this, as I have taken the codeclimate results as a personal challenge and still want to fix them before the weekend, and could simplify this if an ordering requirement is not intended here.

**Comment by tobi-wan-kenobi** [comment]
On first glance, I don't think that widgets needs to be known to the engine before callback registration. As far as I can remember, the widget has a UUID, and that's what's bound to the callback.

**Comment by tobi-wan-kenobi** [comment]
Also: Merging as is, since Travis is fine :) Thanks a lot for the contribution!

**Comment by tobyp** [comment]
Alright, thanks, happy to contribute! Looking forward to the next release :)

**Pull request merged**
