### PR TITLE
Add uptime and public ip tests

### PR DESCRIPTION
**Pull request by izn**
Hey there.

This PR adds some `uptime` and `publicip` module tests. :tada:

Related issue: #641.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
:thumbsup: Very nice, thanks!

btw.: Did you already consider using https://pypi.org/project/pytest-mock/ for mocking? It might ease integration with pytest.

**Comment by izn** [comment]
I will take a look. Tks!

By the way, what do you think about creating a page about writing tests? We can specify which modules we recommend and some test standards.

**Comment by tobi-wan-kenobi** [comment]
Good idea! So far, I thought looking at thecexisting tests is sufficient, but as those grow in size now (thanks!), having a wiki page would be useful. I will try to find time soon to get it started.

If you add someething to the RST structure in docs/, it should qutomatically end up on readthedocs :-)

**Comment by tobi-wan-kenobi** [comment]
@izn I have now updated the documentation somewhat, with at least rudimentary testing guidelines.

Funnily enough, they were present already, just in a non-intuitive location :)

**Comment by izn** [comment]
@tobi-wan-kenobi great! I will take a look soon. ✨

**Pull request merged**
