### PR TITLE
Add nord-powerline theme

### PR DESCRIPTION
**Pull request by uselessthird**
I've added a new theme - hope it's ok.

### CODE REVIEW

**Comment by somospocos** [comment]
Nord theme seems to become quite popular (slowly becoming a fan of it myself).

You may want to expose your work here as well https://github.com/arcticicestudio/nord/projects/1#column-288113 - this place is used for unofficial Nord themes for misc apps.

**Comment by tobi-wan-kenobi** [comment]
Much appreciated, many thanks!

**Comment by tobi-wan-kenobi** [comment]
@somospocos @uselessthird Sample screenshot and addition to README.md already done :)

**Comment by uselessthird** [comment]
@somospocos Great, that was quick work!

**Pull request merged**
