### PR TITLE
Traffic module

### PR DESCRIPTION
**Pull request by meain**
This is simple traffic widget. ( #18 )

TODO: As the speeds change the size of the widget increases and decreases continuously

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Hi,

thanks for the module!

Separate icons: The easiest approach would be to have the module produce two widgets, one for upload, and one for download (like you already do) and give them different states (this is used in the module `cmus` to have prev/next widgets).
Alternatively, we can think about a way to have arbitrarily insertable glyphs in the theme (if I manage to come up with something that doesn't look horrible in the theme spec).

I hope to get around to having a look at #27 this weekend, which would hopefully enable you to fix your "TODO".

This seems to be a module I'd like to have a careful look at before committing (because it's really cool functionality), so please bear with me if it takes a while to merge the PR.

**Comment by meain** [comment]
module:
```python
        widgets = [
            bumblebee.output.Widget(name="traffic.down"),
            bumblebee.output.Widget(name="traffic.up"),
        ]
```

awesome-fonts:
```json
  "traffic":{
	  "down": { "prefix": "" },
	  "up": { "prefix": "" }
  }
```

Anything else I got to get the icon showing up?

**Comment by meain** [comment]
I now has separate up and down speeds.

**Comment by tobi-wan-kenobi** [comment]
Hello,

I have reviewed you module and have some small suggestions, which I'd like to discuss with you. You can find my proposed modifications here: https://github.com/tobi-wan-kenobi/bumblebee-status/tree/meain-traffic

Basically, the changes are:
- Show statistics per NIC (first widget: name of NIC, second: downlink traffic, third: uplink traffic)
- Use `psutil` instead of `ifconfig`, because this removes a dependency (the tool depends on `psutil` for NIC statistics already)
- Add a min-width and alignment setting to the core framework and the widgets to have a nicer display.

Here's an example how the module looks now:
selection_096

If you like it, I can merge that to master.

**Comment by meain** [comment]
I personally think it is better to keep the up and down icons as prefix for the sake of consistency. Apart from that it looks good.

**Comment by tobi-wan-kenobi** [comment]
Good point, I changed that. Thanks a lot for the contribution, that's a nice module that I'll start using immediately :-)

**Pull request merged**
