### PR TITLE
Pactl

### PR DESCRIPTION
**Pull request by bbernhard**
This is just a small little module which displays the current selected default sink allows to select a different one.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Nice, many thanks!

Would it maybe make sense to unify that with the pulseaudio module and/or use this as a basis for a rewrite of the pulseaudio module? What's your opinion on that?

**Comment by bbernhard** [comment]
I also thought about that, but unfortunately the left & right mouse buttons are already in use there:

> Displays volume and mute status and controls for PulseAudio devices. Use wheel up and down to change volume, left click mutes, right click opens pavucontrol.

I guess we could make the left/right mouse button actions configurable (like different modes), but not sure if that would be intuitive to use then?

**Comment by tobi-wan-kenobi** [comment]
Ah, I see, good point.

After thinking about it quite a lot, I still don't know what would be best. Having different modules for the same purpose sounds confusing as well.

What if we did something like this: Mouse actions can be overridden alteady via parameters. If we extens that so that modules can register custom actions, we could have parameters like `pasink.left-click=menu-popup`

What do you think about that? Would that fit your purpose?

**Comment by tobi-wan-kenobi** [comment]
I will just go ahead & merge it, we can always improve the modules later :)

Thanks a lot for the contribution!

**Comment by bbernhard** [comment]
> What if we did something like this: Mouse actions can be overridden alteady via parameters. If we extens that so that modules can register custom actions, we could have parameters like pasink.left-click=menu-popup

> What do you think about that? Would that fit your purpose?

I think that would definitely make sense & would fit my purpose! 

At the moment I am struggling a bit to understand how that would be implemented. I haven't checked the sourcecode yet, but if I understood the [documentation](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/main/docs/features.rst#events) correctly then the mouse action overrides are handled purely by the framework, right?

If I  e.g specify `bumblebee-status -p nic.left-click="pavucontrol"` the framework ensures to invoke the `pavucontrol` executable on a left click. So, there's no logic to implement in the module, right? 

I guess if the `menu-popup` should be handled generically by the framework as well, I guess we need to somehow pass the available dropdown menu options along? Or will there be a concrete `menu-popup` handler that needs to be implemented in the module?

**Comment by tobi-wan-kenobi** [comment]
Right, exactly!

I'm thinking along those lines:

If a custom action is defined, first check if a method with that name is defined for the module (via `getattr()`). If so, invoke it, otherwise try to execute a binary 

I **guess** that should be relatively straight-forward to implent (famous last words)

I'll try to give that a go during the weekend.

**Comment by tobi-wan-kenobi** [comment]
@bbernhard Please see #859 

There's a simple example for the `spacer` module that you can try out like this:

`./bumblebee-status -m spacer -p spacer.left-click=update_text` - basically, the event handler should be the name of the method to invoke, and the method gets exactly one parameter: The event.

Does that help? If so, I'd suggest to drop `pactl` again and extend `pulseaudio` instead, if that is fine with you.

**Comment by bbernhard** [comment]
> @bbernhard Please see #859
> 
> There's a simple example for the `spacer` module that you can try out like this:
> 
> `./bumblebee-status -m spacer -p spacer.left-click=update_text` - basically, the event handler should be the name of the method to invoke, and the method gets exactly one parameter: The event.

Looks good - I think that should work :+1:. Many thanks for the fast implementation!

> If so, I'd suggest to drop `pactl` again and extend `pulseaudio` instead, if that is fine with you.

Sounds good to me :+1:

**Comment by bbernhard** [comment]
> @bbernhard Please see #859
> 
> There's a simple example for the `spacer` module that you can try out like this:
> 
> `./bumblebee-status -m spacer -p spacer.left-click=update_text` - basically, the event handler should be the name of the method to invoke, and the method gets exactly one parameter: The event.
> 
> Does that help? If so, I'd suggest to drop `pactl` again and extend `pulseaudio` instead, if that is fine with you.

This is probably a stupid question, but how do I get the `widget` inside the event handler?

I tried something like this:

```
def __on_sink_selected(self, sink_name):
        logging.info("click")

def select_default_device_popup(self, event):
        logging.info("I am here")
        widget = self.widget()

        menu = util.popup.menu()
        menu.add_menuitem(
                    "hello",
                    callback=functools.partial(self.__on_sink_selected, "hello"),
                )
        menu.show(widget)
```

together with the following config parameter: `pasink.left-click=select_default_device_popup`.

Although the event handler gets called (I see the log message in the log file), I do not see any popup appearing. But I am not sure whether `self.widget()` is the correct way to obtain the widget?

**Comment by tobi-wan-kenobi** [comment]
Hm, that looks like it *should* work, particularly since the pulseaudio modules only have a single widget each.

I woll need to look into this tomorrow...

Can you maybe check the values for seld and widget via logging?

Thanks!

**Comment by tobi-wan-kenobi** [comment]
@bbernhard This is actually a case kf bad naming on my end.

"widget" that is passed to the show() method is actually the "event" (because in a sense, the event represents the widget that was clicked)

Hope that works!

**Comment by bbernhard** [comment]
> @bbernhard This is actually a case kf bad naming on my end.
> 
> "widget" that is passed to the show() method is actually the "event" (because in a sense, the event represents the widget that was clicked)
> 
> Hope that works!

aaah, got it! :grinning: 

Works like a charm now - many thanks!

**Pull request merged**
