### PR TITLE
[Modules/getcrypto] Get crypto prices module 

### PR DESCRIPTION
**Pull request by Ryunaq**
Extremely niche module that will probably never be used for getting the price of BTC, ETH and/or LTC from Kraken.

Btw, this is my first pull request ever so idk if I should do it like I did, anyways, thanks for the awesome bar!

### CODE REVIEW

**Comment by Ryunaq** [comment]
So as I said, I don't know much about pull requests yet but it seems the reason travis is failing the check is because of the module `test_modules.py`, so I'm not sure if I should try to "fix" that.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the contribution! As far as I can see, the PR looks good. Don't worry about Travis, he likes to complain :) Usually, I fix the failing tests while merging.

If I encounter any troubles, I might come back and ask a few questions, but I think it should work out fine. I will need some time to review the changes, but hopefully, I can merge your changes some time this week.

**Comment by Ryunaq** [comment]
Yep, you were right, changed `_curprice=" "` and that fixed the Travis thing. Hope it works out fine too!

**Comment by tobi-wan-kenobi** [comment]
Looks good, thanks a lot!

**Pull request merged**
