### PR TITLE
Order sunrise and sunset according to current time

### PR DESCRIPTION
**Pull request by basvdheuvel**
I'm more interested in what the next sunrise or sunset will be.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Looks good to me, thanks for the PR!

@lonesomebyte537 Is that PR fine for you? I'll wait a few days for your comments before merging.

**Comment by lonesomebyte537** [comment]
> Looks good to me, thanks for the PR!
> 
> @lonesomebyte537 Is that PR fine for you? I'll wait a few days for your comments before merging.
Hi @tobi-wan-kenobi, Yes, it's fine for me. I tried to solve the code climate issues but by doing so I hit other problems (e.g. too many functions). To solve all issues, I need to restructure the whole thing. Will try to do that in a next phase since I still believe these rules make sense.

**Comment by lonesomebyte537** [comment]
Hi @tobi-wan-kenobi, yes, PR is fine for me
Hi @basvdheuvel, thanks, I like your changes, makes sense! 
(in case you saw my comment I deleted in the meantime: forget my remarks... it mixed up things with another PR...)

**Comment by tobi-wan-kenobi** [comment]
Great, then I'll go ahead and merge.

**Pull request merged**
