### PR TITLE
Fix issue number #49 and other improvements.

### PR DESCRIPTION
**Pull request by yashar-sb-sb**
Changes:

Fix issue #49 . [bug - `pacman` freezes the bar]
Add `"rsync"` to recognized protocols for mirrors.
Use `widget`'s store functionality instead of private variables.
Define repository names in a list and reuse them later.
Add pacman to theme.

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
I don't have Arch Linux installed, but Travis says the tests are OK, and the diff looks good.

Maybe @Pseudonick47 can give the changes a go (he's the original contributor of the pacman module).

In the meantime, I'll merge the PR, since it looks fine :-)

Thanks a lot!

**Comment by yashar-sb-sb** [comment]
It was a pleasure working on the project.
I'm planning to make some other improvements to the code when I have the time to do so.

**Comment by tobi-wan-kenobi** [comment]
Glad to hear that & thanks a lot for your contributions!

**Comment by yashar-sb-sb** [comment]
You're welcome.

**Pull request merged**
