### PR TITLE
[modules/thunderbird]: Thunderbird's unread email counts by inbox

### PR DESCRIPTION
**Pull request by cristianmiranda**
I've been using this one for a while now, but never had the time to create a PR. Here it goes 😄 

I have two main inboxes I care about: Personal & Work

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
As a Thunderbird user: Great addition, many thanks!

**Comment by tobi-wan-kenobi** [comment]
What would be a possible addition is some autodetect whether the most common locations ($HOME/.thunderbird, etc) exist, if home is not specified, wuat do you think?

**Comment by cristianmiranda** [comment]
> What would be a possible addition is some autodetect whether the most common locations ($HOME/.thunderbird, etc) exist, if home is not specified, wuat do you think?

I had some trouble using `$HOME/.thunderbird` and `~/.thunderbird`. I'll do some research on how to properly get the current user's home directory so we can use it and remove `thunderbird.home` param.

**Comment by tobi-wan-kenobi** [comment]
@cristianmiranda Yeah, Python is weird in that regards. You have to call `os.path.expanduser()` (I think), so that the path variables are resolved.

Assumedly, that is for security reasons? You can have a look at the code that iterates the theme folders, it makes use of that.

Cheers!

**Pull request merged**
