### PR TITLE
parameter to prevent scrollable decorator from fixing the module width

### PR DESCRIPTION
**Pull request by joshbarrass**

### CODE REVIEW

**Comment by tobi-wan-kenobi** [comment]
Looks good, even though you *could* use the bumblebee.util.asbool() for making the boolean comparison even nicer :)

Thanks!

**Comment by joshbarrass** [comment]
Would it be worth me submitting another PR to switch it over to `bumblebee.util.asbool()`? I don't want to spam you with unnecessary PRs.

**Comment by tobi-wan-kenobi** [comment]
I'd welcome the PR! Otherwise, I'll just fix that with one of my next commits, both work fine for me.

**Comment by joshbarrass** [comment]
Okay, I'll put a PR together.

**Pull request merged**
